use crate::lazy::byte_set::{set_bits, ByteSet};

#[derive(PartialEq, Debug, Default)]
pub(crate) struct Prefilter {
    /// Matrix of 256 rows x number of u64 needed to handle every bit that needs to be set
    table: Vec<u64>,
    /// Number of u64 per row of `table`
    stride: usize,
    /// Union of every pattern byte set: does byte i has a pattern matching?
    quick_lookup: ByteSet,
}

impl Prefilter {
    /// Builds a prefilter from the given list of [ByteSet]
    /// If there are no actual ByteSet, returns None.
    /// Otherwise returns the built prefilter along with the indices that are NOT contained
    /// in the prefilter.
    pub(crate) fn from_byte_sets(sets: &[Option<ByteSet>]) -> Option<(Self, Vec<usize>)> {
        if sets.is_empty() {
            return None;
        }

        let stride = (sets.len() + 63) / 64;
        let mut table = vec![0u64; 256 * stride];
        let mut quick_lookup = ByteSet::new();
        let mut unqualified = Vec::new();
        let mut something_qualified = false;

        for (idx, set) in sets.iter().enumerate() {
            let set = match set.as_ref() {
                Some(set) => set,
                None => {
                    unqualified.push(idx);
                    continue;
                }
            };
            something_qualified = true;
            quick_lookup.union(set);

            let (word_idx, bit) = (idx / 64, 1u64 << (idx % 64));
            for b in set.iter() {
                table[b as usize * stride + word_idx] |= bit;
            }
        }

        if !something_qualified {
            return None;
        }

        Some((
            Self {
                table,
                stride,
                quick_lookup,
            },
            unqualified,
        ))
    }

    /// Whether any pattern in the prefilter can start with that byte
    #[inline]
    pub(crate) fn may_match_at(&self, byte: u8) -> bool {
        self.quick_lookup.contains(byte)
    }

    /// The pattern indices this byte can match, in ascending order
    #[inline]
    pub(crate) fn candidates(&self, byte: u8) -> impl Iterator<Item = usize> + '_ {
        let start = byte as usize * self.stride;
        set_bits(&self.table[start..start + self.stride])
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lazy::byte_set::byte_set_from_expr;
    use crate::{Expr, RegexOptions};

    fn get_byte_set_from_pattern(pattern: &str, options: &RegexOptions) -> Option<ByteSet> {
        let tree = Expr::parse_tree_with_flags(pattern, options.compute_flags()).ok()?;
        byte_set_from_expr(&tree.expr, options)
    }

    fn first_bytes_of(pattern: &str) -> Option<Vec<u8>> {
        let set = get_byte_set_from_pattern(pattern, &RegexOptions::default())?;
        Some(set.iter().collect())
    }

    #[test]
    fn can_extract_ascii_byteset_from_pattern() {
        let inputs = vec![
            (r"fn", Some(vec![b'f'])),
            (r"::", Some(vec![b':'])),
            (r"=>", Some(vec![b'='])),
            (r"\{", Some(vec![b'{'])),
            (r"fn|let|impl", Some(vec![b'f', b'i', b'l'])),
            (r"(fn|let|impl)", Some(vec![b'f', b'i', b'l'])),
            (r"(?:->|<-)", Some(vec![b'-', b'<'])),
            (r"\bfn\b", Some(vec![b'f'])),
            (r"^let", Some(vec![b'l'])),
            (r"\Gx", Some(vec![b'x'])),
            (r"(?<!\.)let", Some(vec![b'l'])),
            (r"[abc]x", Some(vec![b'a', b'b', b'c'])),
            (r"[a-d]", Some(vec![b'a', b'b', b'c', b'd'])),
            (r"(?i)fn", Some(vec![b'F', b'f'])),
            (r"(?i)[a-b]", Some(vec![b'A', b'B', b'a', b'b'])),
            (r"&(?![&=])", Some(vec![b'&'])),
            (r"(?x) fn # comment", Some(vec![b'f'])),
            (r"(?=\[)", Some(vec![b'['])),
            (r"(?=.*)x", Some(vec![b'x'])),
            (r"(?=a?)x", Some(vec![b'x'])),
            (r"(?!x)a", Some(vec![b'a'])),
            (r#"(?=["'`])""#, Some(vec![b'"', b'\'', b'`'])),
            (r#"(?=ab|xy)"#, Some(vec![b'a', b'x'])),
            (r#"r?""#, Some(vec![b'"', b'r'])),
            (r"a+", Some(vec![b'a'])),
            (r"(?>fn)", Some(vec![b'f'])),
            (r"\Kfn", Some(vec![b'f'])),
            (r"über", Some(vec![0xC3])),
            (r"a?", None),
            (r"(?!x)", None),
            (r".", None),
            (r".*x", None),
            (r"\R", None),
            (r"(", None),
            // Cases generated by Claude for (?i)
            // Unicode simple folding: (?i)s also matches ſ (U+017F, lead 0xC5)
            (r"(?i)sort", Some(vec![b'S', b's', 0xC5])),
            // and (?i)k also matches K (U+212A KELVIN SIGN, lead 0xE2)
            (r"(?i)kind", Some(vec![b'K', b'k', 0xE2])),
            // the closure works from the non-ASCII side too
            (r"(?i)ſ", Some(vec![b'S', b's', 0xC5])),
            // é folds to {é, É}, both with starting with 0xC3
            (r"(?i)é", Some(vec![0xC3])),
        ];

        for (input, expected) in inputs {
            assert_eq!(first_bytes_of(input), expected);
        }
    }

    #[test]
    fn can_extract_byteset_from_unicode() {
        let upper = first_bytes_of(r"\p{upper}!").unwrap();
        assert!(upper.contains(&b'A') && upper.contains(&b'Z'));
        assert!(!upper.contains(&b'a') && !upper.contains(&b'!'));
        // unicode lead byte is present
        assert!(upper.contains(&0xC3));

        let not_upper = first_bytes_of(r"\P{upper}!").unwrap();
        assert!(not_upper.contains(&b'a') && not_upper.contains(&b'z'));
        // ! is not uppercase so it can be the first match
        assert!(!not_upper.contains(&b'A') && not_upper.contains(&b'!'));
        // something not recognised is just nothing for the prefilter
        assert!(first_bytes_of(r"\P{typo}!").is_none());
    }

    #[test]
    fn can_extract_byteset_from_negation() {
        let b1 = first_bytes_of(r"[^a-c]x").unwrap();
        assert!(!b1.contains(&b'a') && !b1.contains(&b'c'));
        assert!(b1.contains(&b'd') && b1.contains(&b' ') && b1.contains(&0xC3));

        let b2 = first_bytes_of(r"(?i)[^a]").unwrap();
        assert!(!b2.contains(&b'a') && !b2.contains(&b'A') && b2.contains(&b'b'));

        let b3 = first_bytes_of(r"[^[:alpha:]]").unwrap();
        assert!(!b3.contains(&b'a') && !b3.contains(&b'Z'));
        assert!(b3.contains(&b'0') && b3.contains(&b' ') && b3.contains(&0xC3));
    }

    fn byte_sets(patterns: &[&str]) -> Vec<Option<ByteSet>> {
        patterns
            .iter()
            .map(|p| get_byte_set_from_pattern(p, &RegexOptions::default()))
            .collect()
    }

    #[test]
    fn can_build_prefilter() {
        // `.` has no start bytes so it stays out of the table
        let sets = byte_sets(&["fn", "let|impl", ".", "\\{"]);
        let (prefilter, unqualified) = Prefilter::from_byte_sets(&sets).unwrap();
        assert_eq!(unqualified, vec![2]);

        assert!(prefilter.may_match_at(b'f'));
        assert!(prefilter.may_match_at(b'l'));
        assert!(!prefilter.may_match_at(b'x'));

        assert_eq!(prefilter.candidates(b'f').collect::<Vec<_>>(), vec![0]);
        assert_eq!(prefilter.candidates(b'i').collect::<Vec<_>>(), vec![1]);
        assert_eq!(prefilter.candidates(b'{').collect::<Vec<_>>(), vec![3]);
        assert!(prefilter.candidates(b'x').next().is_none());
    }

    #[test]
    fn prefilter_handles_more_than_one_word_per_row() {
        // 70 patterns means 2 u64 per row, so the last ones live in the second word
        let mut patterns: Vec<String> = (0..70).map(|i| format!("a{}", i)).collect();
        patterns[69] = "z".to_string();
        let sets: Vec<_> = patterns
            .iter()
            .map(|p| get_byte_set_from_pattern(p, &RegexOptions::default()))
            .collect();
        let (prefilter, unqualified) = Prefilter::from_byte_sets(&sets).unwrap();

        assert!(unqualified.is_empty());
        assert_eq!(prefilter.candidates(b'z').collect::<Vec<_>>(), vec![69]);
        assert_eq!(prefilter.candidates(b'a').count(), 69);
    }

    #[test]
    fn no_prefilter_when_nothing_qualifies() {
        assert!(Prefilter::from_byte_sets(&[]).is_none());
        assert!(Prefilter::from_byte_sets(&byte_sets(&[".", "a?"])).is_none());
    }
}
